### ISSUE TITLE
Add Sources

### ISSUE THREAD

**Issue by Shaun-Regenbaum** [Shaun-Regenbaum/tf_db#2]
Where did we get the initial DB from?
Where did we get the metabolic gene list from?

**Comment by jonahdiamond** [comment]
Sources of the columns of the database:

{Ensembl ID, HGNC symbol, DBD, TF assessment, Binding mode, Motif Status, Final Notes, Final Comments, Interpro ID(s), EntrezGene ID, EntrezGene Description, PDB ID, TF tested by HT-SELEX?, TF tested by PBM?, Conditional Binding Requirements, Original Comments, Vaquerizas 2009 classification, CisBP considers it a TF?, TFcat classification, Is a GO TF?, Initial assessment, Curator 1, Curator 2, TFclass considers it a TF?, Go Evidence, Pfam Domains (By ENSP ID), Is C2H2 ZF(KRAB)?, Is TF}
- [UofT Database](http://humantfs.ccbr.utoronto.ca/download.php)

{Related Genes HGNC}
- [[ARCHS4_Coexpression.csv](https://github.com/Shaun-Regenbaum/tf_db/files/12331197/ARCHS4_Coexpression.csv)]

Source of metabolic gene list:
- [MMED](https://esbl.nhlbi.nih.gov/Databases/KSBP2/Targets/Lists/MetabolicEnzymes/MetabolicEnzymeDatabase.html)
